name: Build Release

on: 
  workflow_dispatch:

env:
  packageName: "la.niri.videoplayer"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      package_name: ${{ steps.set_outputs.outputs.package_name }}
      version: ${{ steps.set_outputs.outputs.version }}
        
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
        
      - name: Create Zip
        run: zip -r "$ZIP_NAME" . -x '.*'
        env:
          ZIP_NAME: "${{env.zipFile}}" 

      - name: Create VPAI Package
        run: curl -sL "https://api.anatawa12.com/create-vpai/?repo=https%3A%2F%2Fvpm.niri.la%2Fvpm.json&package=$packageName&version=${{ steps.set_outputs.outputs.version }}" > "$unityPackage"
      
      - name: Extract release notes
        id: release_notes
        run: |
          RELEASE_NOTES="## Version ${{ steps.version.outputs.prop }}"$'\n'
          CURRENT_LINE=0
          while IFS= read -r line; do
            if [[ "$line" == "## ${{ steps.version.outputs.prop }} - "* ]]; then
              CURRENT_LINE=1
            elif [[ "$CURRENT_LINE" == 1 && "$line" == "## "* ]]; then
              CURRENT_LINE=0
            elif [[ "$CURRENT_LINE" == 1 ]]; then
              RELEASE_NOTES+="$line"$'\n'
            fi
          done < "CHANGELOG.md"
          echo "$RELEASE_NOTES" > release_notes_diff.txt
  
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          name: v${{ steps.version.outputs.prop }}
          body_path: ${{ github.workspace }}/release_notes_diff.txt
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            package.json
      - name: Set outputs
        id: set_outputs
        run: |
          echo "version=${{ steps.version.outputs.prop }}" >> "$GITHUB_OUTPUT"

  publish-vpm:
    uses: niwaniwa/vpm.niri.la/.github/workflows/update.yml@main
    needs: [build]
    with:
      repository_name: KineLVideoPlayer
      version: ${{ needs.build.outputs.version }}
    secrets:
      access-token: ${{ secrets.ACCESS_REPO }}
